#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Digest-Whirlpool
version:      1.0.2
version_from: Whirlpool.pm
installdirs:  site
requires:
    MIME::Base64:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_03
